version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    tty: true
    stdin_open: true
    networks:
      - lab_task


  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    container_name: fastapi_task
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - lab_task

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=info
    container_name: celery_app
    volumes:
      - .:/app
    depends_on:
      - api
      - redis
    networks:
      - lab_task

networks:
  lab_task:
    driver: bridge