version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    tty: true
    stdin_open: true
    networks:
      - lab_task

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    container_name: fastapi_task
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - lab_task

  celery_tasks:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=info
    container_name: celery_tasks
    volumes:
      - .:/app
    depends_on:
      - fastapi
      - redis
    networks:
      - lab_task

  celery_scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks beat --loglevel=info
    container_name: celery_scheduler
    # volumes:
    #   - ./scheduler:/app
    depends_on:
      - fastapi
      - redis
    networks:
      - lab_task

networks:
  lab_task:
    driver: bridge